// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd4VH_ZmRAuFGKHgIjZ4NIKEbS43qzq78',
    appId: '1:747191488222:web:80761e41135aed9a1d7c4f',
    messagingSenderId: '747191488222',
    projectId: 'dilara-77846',
    authDomain: 'dilara-77846.firebaseapp.com',
    storageBucket: 'dilara-77846.firebasestorage.app',
    measurementId: 'G-G9JY944GCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCts5stv6d76OZt_j4A5uyXjEzx8f0Msm4',
    appId: '1:747191488222:android:61b8550e2e4167551d7c4f',
    messagingSenderId: '747191488222',
    projectId: 'dilara-77846',
    storageBucket: 'dilara-77846.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALL_58_KBl58eQ8yulo6q-ZLRkGElDgeM',
    appId: '1:747191488222:ios:7b379c403e62c82a1d7c4f',
    messagingSenderId: '747191488222',
    projectId: 'dilara-77846',
    storageBucket: 'dilara-77846.firebasestorage.app',
    iosBundleId: 'net.dilara.social',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALL_58_KBl58eQ8yulo6q-ZLRkGElDgeM',
    appId: '1:747191488222:ios:04670581bb8a14ae1d7c4f',
    messagingSenderId: '747191488222',
    projectId: 'dilara-77846',
    storageBucket: 'dilara-77846.firebasestorage.app',
    iosBundleId: 'com.example.dilaraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd4VH_ZmRAuFGKHgIjZ4NIKEbS43qzq78',
    appId: '1:747191488222:web:95d16de6456a953d1d7c4f',
    messagingSenderId: '747191488222',
    projectId: 'dilara-77846',
    authDomain: 'dilara-77846.firebaseapp.com',
    storageBucket: 'dilara-77846.firebasestorage.app',
    measurementId: 'G-KZF1T13087',
  );
}
